@local = http://localhost:3000/auth/
@api = http://localhost:3000/api

@tokenTemp = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InJvbGUiOjAsImlkIjoxMSwibmFtZSI6Impvc2VlZSIsImVtYWlsIjoidGFjYWNob2pvc2VAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkMzFNazFlNWhhOGg5bUV4MDJTMzV2dW1vZ291ZUJPNW5LeUlnc0ZqT3k4bXF4eWo5aVNjWnkifSwiaWF0IjoxNjMxNTcwNzg1LCJleHAiOjE2MzE2NTcxODV9.z8DTffB805o_KkOob9o4d3ufNq58ZKQIAH_wApLZDdU
### POST crear usuario 
POST {{local}}/register
Content-Type: application/json

{
  "name": "joseee",
  "password": "123456",
  "email":"tacachojose@gmail.com"
}

### GET logearse 

GET {{local}}/login
Content-Type:  application/json

{
  "email":"tacachojose@gmail.com",
  "password": "123456"
}

### CHARACTERS /////////////////////////////////////////////////////////////////

POST {{api}}/characters HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: jwt {{tokenTemp}}

nombre=AAAAAAA&edad=60&peso=60&historia=Lorem_.&titulo=volver al pasado 1&fechaDeCreacion=2010-12-31&calificacion=5


### GET TODOS LOS PERSONAJES 
GET {{api}}/characters HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: jwt {{tokenTemp}}

### GET 1 PERSONAJE POR ID 

GET {{api}}/characters/1 HTTP/1.1
Content-Type:  application/x-www-form-urlencoded
Authorization: jwt {{tokenTemp}}

### POST 1 ACTUALIZAR 1 PERSONAJE 

PATCH {{api}}/characters/1 HTTP/1.1
Content-Type:  application/x-www-form-urlencoded
Authorization: jwt {{tokenTemp}}

nombre=CCCCC

### GET 1 PERSONAJE POR ID 

DELETE {{api}}/characters/19 HTTP/1.1
Content-Type:  application/x-www-form-urlencoded
Authorization: jwt {{tokenTemp}}

### MOVIES ////////////////////////////////////////////////////////////////////

POST {{api}}/movies HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: jwt {{tokenTemp}}

titulo=NDEAA&fechaDeCreacion=2010-12-31&calificacion=4&nombre=jorge&edad=20&peso=10&historia=eraCurioso

### GET ALL MOVIES 
GET {{api}}/movies HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: jwt {{tokenTemp}}

### 
GET {{api}}/movies/1 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: jwt {{tokenTemp}}

### 
PATCH  {{api}}/movies/1 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: jwt {{tokenTemp}}

titulo=PONELE

### GET 1 PERSONAJE POR ID 

DELETE {{api}}/movies/4 HTTP/1.1
Content-Type:  application/x-www-form-urlencoded
Authorization: jwt {{tokenTemp}}

### GENDERS ////////////////////////////////////////////////////////////////////

POST {{api}}/genders HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: jwt {{tokenTemp}}

nombre=terror&titulo=NDEAA&fechaDeCreacion=2010-12-31&calificacion=4


### Get all genders 
GET {{api}}/genders HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: jwt {{tokenTemp}}

### GET 1 PERSONAJE POR ID

GET {{api}}/genders/1 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: jwt {{tokenTemp}}

### UPDATE 1 PERSONAJE POR ID

PATCH {{api}}/genders/1 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: jwt {{tokenTemp}}

nombre=DDDDDD

### 

DELETE {{api}}/genders/1 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: jwt {{tokenTemp}}

###

GET {{api}}/genders/terror HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: jwt {{tokenTemp}}

